export const receiptOperationalScalarSelect = {
  id: true,
  tenantId: true,
  no: true,
  storeId: true,
  supplierId: true,
  deliveryDate: true,
  totalAmount: true,
  status: true,
  note: true,
  createdById: true,
  confirmedAt: true,
  isManual: true,
  tempSupplierName: true,
  rejectReason: true,
  rejectedAt: true,
  purchaseOrderId: true,
  deliveryOrderId: true,
  invoiceId: true,
  supplierVerifiedAt: true,
  supplierVerifiedById: true,
  supplierVerifyNote: true,
  financeVerifiedAt: true,
  financeVerifiedById: true,
  financeVerifyNote: true,
  createdAt: true,
  updatedAt: true,
} as const

export const receiptPaymentScheduleSelect = {
  id: true,
  status: true,
  dueAt: true,
  amount: true,
} as const
